export const ProjectsMap = [{
        id: 1,
        headerImg: ["tienda", "../assets/img/tienda.png"],
        imgTitle: ["tienda"],
        title: "Tienda",
        toolsUsed: ["PS, Figma, Behance"],
        details: "details",
        shoots: ["greek", "../assets/img/greek.png"],
    },
    {
        id: 2,
        headerImg: ["../assets/img/greek.png"],
        imgTitle: ["weatherly"],
        title: "Tienda",
        toolsUsed: ["PS, Figma, Behance"],
        details: "details",
        shoots: ["greek", "../assets/img/greek.png"],
    },
    {
        id: 3,
        headerImg: ["../assets/img/greek.png"],
        imgTitle: ["jpadel"],
        title: "Tienda",
        toolsUsed: ["PS, Figma, Behance"],
        details: "details",
        shoots: ["greek", "../assets/img/greek.png"],
    },
    {
        id: 4,
        headerImg: ["../assets/img/greek.png"],
        imgTitle: ["grind"],
        title: "Tienda",
        toolsUsed: ["PS, Figma, Behance"],
        details: "details",
        shoots: ["greek", "../assets/img/greek.png"],
    },
    {
        id: 5,
        headerImg: ["../assets/img/greek.png"],
        imgTitle: ["logofolio"],
        title: "Tienda",
        toolsUsed: ["PS, Figma, Behance"],
        details: "details",
        shoots: ["greek", "../assets/img/greek.png"],
    },
    {
        id: 6,
        headerImg: ["../assets/img/greek.png"],
        imgTitle: ["xplore"],
        title: "Tienda",
        toolsUsed: ["PS, Figma, Behance"],
        details: "details",
        shoots: ["greek", "../assets/img/greek.png"],
    },
    {
        id: 7,
        headerImg: ["../assets/img/greek.png"],
        imgTitle: ["bandb"],
        title: "Tienda",
        toolsUsed: ["PS, Figma, Behance"],
        details: "details",
        shoots: ["greek", "../assets/img/greek.png"],
    },
    {
        id: 8,
        headerImg: ["../assets/img/greek.png"],
        imgTitle: ["akary"],
        title: "Tienda",
        toolsUsed: ["PS, Figma, Behance"],
        details: "details",
        shoots: ["greek", "../assets/img/greek.png"],
    },
];